export const QuoteList = [
  "Lost in pages…",
  "Bookworm mode: Activated.",
  "Just one more chapter…",
  "Plot twist loading…",
  "Mind in progress, please wait.",
  "Currently lost in a story.",
  "Loading imagination…",
  "Brain powered by books.",
  "Hold on, plot unfolding.",
  "Reading: Getting smarter.",
  "Chapter complete, next one loading.",
  "Adventure awaits. Loading…",
  "Books are my WiFi.",
  "Please wait. Story in process.",
  "Eyes on pages, brain in another world.",
  "Plot being built, please hold.",
  "Currently bookmarking reality.",
  "Plotting my escape…",
  "The adventure is just beginning.",
  "Book in hand, world on pause.",
  "Warning: book-induced daydreaming in progress.",
  "Reading: Prepare for adventure.",
  "Once upon a time… loading.",
  "Brain loading: One chapter at a time.",
  "Sinking into a good book.",
  "Books: My favorite getaway.",
  "The next chapter is a mystery.",
  "Whispers of the plot in progress…",
  "Mind: 99% lost in a book.",
  "Curiosity loading…",
  "Pause the world, I’m reading.",
  "Next chapter loading…",
  "Waiting for the story to surprise me.",
  "Page-turning progress…",
  "Plot loading, please do not disturb.",
  "Loading: New world incoming.",
  "Next adventure in progress.",
  "Story in the making…",
  "Lost in thought… one page at a time.",
  "Reading is my favorite distraction.",
  "Book: Ready to transport me.",
  "Novel loading… imagination at work.",
  "Brain overload: Too many books.",
  "One page closer to the end.",
  "Story buffering…",
  "Plot unfolding, stay tuned.",
  "Chapter by chapter, please wait.",
  "Currently escaping in pages.",
  "Thoughts loading, please be patient.",
  "World on pause. Story on play.",
];
